# BetterReset configuration

confirmation:
  # Require a second, explicit confirmation before running a reset command
  requireConfirm: true
  # How long the confirmation is valid (seconds)
  timeoutSeconds: 15

seeds:
  # If true, use the same seed for overworld/nether/end when a seed is provided or generated.
  useSameSeedForAllDimensions: true

players:
  # After reset and recreation, return affected players to the new overworld spawn
  returnToNewSpawnAfterReset: true

messages:
  noPermission: "&cYou don't have permission to use this command."
  confirmationWarning: "&c[WARNING] This will DELETE and REGENERATE &e%world% &coverworld, nether, and end while the server is running!"
  confirmationHowTo: "&7Type &e/%label% %world% confirm &7within &e%seconds%s &7to proceed."
  countdownTitle: "&cReset in %s..."
  countdownSubtitle: "&7plugin made by muj3b"

countdown:
  seconds: 10
  # If true, show countdown titles to all players. If false, only to players in affected dimensions.
  broadcastToAll: true

teleport:
  # Name of a safe fallback world to send players before deletion. Leave blank to auto-pick/create.
  fallbackWorldName: ""

limits:
  # Prevent resets if more than this many players are online (-1 to disable)
  maxOnlineForReset: -1

confirmation:
  # If true, console commands skip confirmation
  consoleBypasses: true

backups:
  # Keep at most this many snapshots per base world (older are pruned)
  maxPerBase: 5
  # Keep at most this many snapshots total across all bases
  maxTotal: 50
  # Delete snapshots older than this many days
  maxAgeDays: 30
