name: BetterReset
version: 1.0.2
main: com.github.codex.fullreset.FullResetPlugin
api-version: '1.21'
author: muj3b
description: Reset a world's overworld, nether, and end live with one command.
softdepend:
  - Multiverse-Core

commands:
  betterreset:
    description: BetterReset root command
    usage: /betterreset <fullreset|gui|reload|creator|status|stats|cancel|fallback|seedsame|listworlds|about|prune|deleteallbackups|preload|testreset|seeds> [...]
    aliases: [br]
    permission: betterreset.use

permissions:
  betterreset.use:
    description: Allows using /betterreset fullreset
    default: op
  betterreset.gui:
    description: Allows /betterreset gui
    default: op
  betterreset.reload:
    description: Allows /betterreset reload
    default: op
  betterreset.creator:
    description: Allows /betterreset creator
    default: true
  betterreset.status:
    description: Allows /betterreset status
    default: true
  betterreset.stats:
    description: Allows /betterreset stats
    default: true
  betterreset.cancel:
    description: Allows /betterreset cancel (countdown only)
    default: op
  betterreset.fallback:
    description: Allows /betterreset fallback <world>
    default: op
  betterreset.seedsame:
    description: Allows /betterreset seedsame <true|false>
    default: op
  betterreset.listworlds:
    description: Allows /betterreset listworlds
    default: true
  betterreset.about:
    description: Allows /betterreset about
    default: true
  betterreset.seeds:
    description: Allows /betterreset seeds <list|use>
    default: op
  betterreset.bypassconfirm:
    description: Allows bypassing confirmation for /betterreset fullreset
    default: op
  betterreset.force:
    description: Allows using --force to skip confirmation
    default: op
  betterreset.notify:
    description: Receives start/finish reset notifications
    default: op
  betterreset.prune:
    description: Allows /betterreset prune [base]
    default: op
  betterreset.backups:
    description: Allows deleting backups via GUI
    default: op
  betterreset.deleteallbackups:
    description: Allows /betterreset deleteallbackups [base]
    default: op
  betterreset.preload:
    description: Allows /betterreset preload <on|off|status>
    default: op
  betterreset.test:
    description: Allows /betterreset testreset <base> [--seed <long>]
    default: op
