name: BetterReset
version: 1.0.0
main: com.github.codex.fullreset.FullResetPlugin
api-version: '1.21'
author: muj3b
description: Reset a world's overworld, nether, and end live with one command.
softdepend:
  - Multiverse-Core

commands:
  betterreset:
    description: BetterReset root command
    usage: /betterreset <fullreset|gui|reload> [...]
    aliases: [br]
    permission: betterreset.use
  fullreset:
    description: Legacy alias; use /betterreset fullreset
    usage: /betterreset fullreset <world> [confirm|--confirm] [--seed <long>|--seed random]
    permission: betterreset.use

permissions:
  betterreset.use:
    description: Allows using /betterreset fullreset
    default: op
  betterreset.gui:
    description: Allows /betterreset gui
    default: op
  betterreset.reload:
    description: Allows /betterreset reload
    default: op
